# version: "3.9"

# services:
#   mlflow:
#     build: ./mlflow
#     container_name: mlops-house-pricing-mlflow
#     ports:
#       - "5000:5000"
#     volumes:
#       - mlflow_store:/mlflow
#     environment:
#       - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
#       - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:5000/"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   trainer:
#     build: ./trainer
#     container_name: mlops-house-pricing-trainer
#     depends_on:
#       mlflow:
#         condition: service_healthy
#     environment:
#       - MLFLOW_TRACKING_URI=http://mlflow:5000
#       - ARTIFACT_PATH=/app/models/model.joblib
#     volumes:
#       - models:/app/models
#       - mlflow_store:/mlflow
#     restart: "no"  # one-time execution job

#   api:
#     build: ./api
#     container_name: mlops-house-pricing-api
#     depends_on:
#       mlflow:
#         condition: service_healthy
#       trainer:
#         condition: service_completed_successfully
#     ports:
#       - "8000:8000"
#     environment:
#       - MODEL_PATH=/app/models/model.joblib
#     volumes:
#       - models:/app/models

# volumes:
#   models:
#   mlflow_store:



services:
  mlflow:
    build: ./mlflow
    image: mlops-house-pricing-mlflow:latest   # ✅ Explicit image tag
    container_name: mlops-house-pricing-mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_store:/mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  trainer:
    build: ./trainer
    image: mlops-house-pricing-trainer:latest  # ✅ Explicit image tag
    container_name: mlops-house-pricing-trainer
    depends_on:
      mlflow:
        condition: service_healthy
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - ARTIFACT_PATH=/app/models/model.joblib
    volumes:
      - models:/app/models
      - mlflow_store:/mlflow
      - ./data:/app/data        # ✅ Mount dataset folder
    restart: "no"  # one-time execution job

  api:
    build: ./api
    image: mlops-house-pricing-api:latest       # ✅ Explicit image tag
    container_name: mlops-house-pricing-api
    depends_on:
      mlflow:
        condition: service_healthy
      trainer:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/model.joblib
    volumes:
      - models:/app/models

volumes:
  models:
  mlflow_store:
