name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: mlops_house_pricing

jobs:
  build-train-push:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4️⃣ Build images for all services in docker-compose
    - name: Build MLflow + API + Trainer containers
      run: |
        docker compose build --pull --progress=plain

    # 5️⃣ Run Training step and fail if trainer fails
    - name: Run Trainer
      run: |
        docker compose up --abort-on-container-exit trainer
        docker compose ps

    # 6️⃣ Determine service image names dynamically
    - name: Tag and Push API image
      run: |
        docker compose build api
        docker tag mlops-house-pricing-api:latest ${{ secrets.DOCKERHUB_USERNAME }}/mlops-house-pricing-api:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-house-pricing-api:latest

    - name: Tag and Push Trainer image
      run: |
        docker compose build trainer
        docker tag mlops-house-pricing-trainer:latest ${{ secrets.DOCKERHUB_USERNAME }}/mlops-house-pricing-trainer:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-house-pricing-trainer:latest


    # 7️⃣ Cleanup all containers and volumes
    - name: Cleanup
      run: docker compose down -v --remove-orphans
